import Head from 'next/head';
import NextLink from 'next/link';
import Card from '@/components/cards'
import { Link } from '@chakra-ui/react';
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={roboto.className}>
        <Link as={NextLink} href="/decks/1">
          <Card
            imageUrl="https://via.placeholder.com/450x450"
            sentence="The cat is on the table"
          />
        </Link>
      </main>
    </>
  )
}
